import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { StyledFish1, StyledFish2 } from "../components/Home/StyledFish";
import { HomeContainer } from "../components/Home/HomeContainer";
import { HomeMain } from "../components/Home/HomeMain";
import { HomePic } from "../components/Home/HomePic";
import { BigText, SmallText } from "../components/Home/HomeTexts";


export default function Home() {
  const [state, setState] = useState({
    isScrolling: false,
    clientX: 0,
    scrollX: 0,
  });

  const [xPosition, setXposition] = useState(0)
  
  function catchX (e) {
    setXposition(e.nativeEvent.clientX)
  }
    


  return (
    <HomeContainer onMouseMove={(e)=>{catchX(e)}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePic>
        <Image
          src="/background/pngtree-beautiful-hand-painted-underwater-world-and-plant-background-design-paintedunderwaterplantbeamadvertising-backgroundbackground-image_58115.jpg"
          alt="Picture of the author"
          layout={"fill"}
        />
      </HomePic>
      <HomeMain >
        <BigText>Welcome to my portfolio {xPosition}</BigText>
        <SmallText>
          here you can see some of my skills
        </SmallText>
        <StyledFish1>
          <Image
            src="/fish/499-4998515_pamaypay-clipart-fish-fish-yellow-clip-art-at.png"
            alt="Picture of fish"
            layout={"responsive"}
            height={100}
            width={100}
          />
        </StyledFish1>
        <StyledFish2 xPosition={xPosition}>
        <Image
          src="/fish/Blue_Fish_PNG_Clipart-3023.png"
          alt="Picture of fish"
          layout={"responsive"}
          height={150}
          width={150}
        />
      </StyledFish2>
      </HomeMain>
    </HomeContainer>
  );
}
